    # .streamlit/config.toml

    [server]
    headless = true
    enableCORS = false
    port = 8501

    [logger]
    level = "info"

    [browser]
    gatherUsageStats = false

    [client]
    toolbarMode = "minimal"

    [global]
    dataFrameSerialization = "legacy"

    [runner]
    magicEnabled = true
    fastReruns = false
    installTracer = false

    # Explicitly set a compatible Python version for pandas_ta
    # pandas_ta version 0.3.14b requires Python <3.12, so 3.11 is chosen.
    python_version = "3.11"
    
